.PHONY: production-replay replay-production

TRANSACTIONS ?= 1000
MULTIPLIER ?= 3600
DATA_ROOT ?= /Users/kwilson/Desktop/ITC/fraud_data
MAX_IN_FLIGHT ?= 50
CHECKPOINT_EVERY ?= 100
DURATION ?=
HOURS ?=
DAYS ?=
WEEKS ?=

production-replay:
	FRAUD_DATA_ROOT="$(DATA_ROOT)" \
	PRODUCTION_REPLAY_TRANSACTIONS="$(TRANSACTIONS)" \
	PRODUCTION_REPLAY_MULTIPLIER="$(MULTIPLIER)" \
	PRODUCTION_REPLAY_MAX_IN_FLIGHT="$(MAX_IN_FLIGHT)" \
	PRODUCTION_REPLAY_CHECKPOINT_EVERY="$(CHECKPOINT_EVERY)" \
	PRODUCTION_REPLAY_DURATION="$(DURATION)" \
	PRODUCTION_REPLAY_HOURS="$(HOURS)" \
	PRODUCTION_REPLAY_DAYS="$(DAYS)" \
	PRODUCTION_REPLAY_WEEKS="$(WEEKS)" \
	./backend/stress-tests/production_replay/run_local_replay.sh

replay-production: production-replay
