.PHONY: production-replay replay-production production-replay-async production-replay-ec2 replay-production-ec2 production-replay-ec2-async production-replay-matrix callback-server create-decisions create-async-decisions consolidate-postgres-db

TRANSACTIONS ?= 1000
MULTIPLIER ?= 3600
DATA_ROOT ?= /Users/kwilson/Desktop/ITC/fraud_data
SEED_DATA_ROOT ?= $(patsubst %/,%,$(DATA_ROOT))_seed
MAX_IN_FLIGHT ?= 50
CHECKPOINT_EVERY ?= 100
SEED_BATCH_SIZE ?= 500
SEED_MAX_IN_FLIGHT ?= 10
SEED_PROGRESS_EVERY ?= 100
SEED_REQUEST_TIMEOUT ?= 300
REUSE_EXISTING_SETUP ?= false
DECISION_MODE ?= sync
ASYNC_WAIT_TIMEOUT_MS ?= 0
ASYNC_CALLBACK_PORT ?= 8099
ASYNC_CALLBACK_URL ?= http://host.docker.internal:$(ASYNC_CALLBACK_PORT)/callbacks/async-decisions
ASYNC_CALLBACK_WAIT_TIMEOUT ?= 120
LIVE_DECISION_MODE ?= async_only
LIVE_ASYNC_FALLBACK_ENABLED ?= true
LIVE_ASYNC_OBJECT_TYPES ?=
TENANT_DATA_READ_MODE ?= ingestion_http
ENABLE_SEPARATE_READ_POOL ?= false
READ_DATABASE_URL ?=
READ_DATABASE_MAX_CONNS ?= 0
READ_DATABASE_MIN_CONNS ?= 0
WORKER_DATABASE_URL ?=
WORKER_DATABASE_MAX_CONNS ?= 0
WORKER_DATABASE_MIN_CONNS ?= 0
EXPERIMENT_LABEL ?=
CAPTURE_METRICS ?= false
CALLBACK_HOST ?= 0.0.0.0
CALLBACK_PORT ?= $(ASYNC_CALLBACK_PORT)
CALLBACK_OUTPUT ?= /tmp/fraud-data-local-async-callbacks.ndjson
CALLBACK_LOG ?= /tmp/fraud-data-local-callback-server.log
COUNT ?= 100
PROGRESS_EVERY ?= 100
DECISION_CREATE_OUTPUT ?= /tmp/fraud-decision-create-results.ndjson
DECISION_CREATE_EVENT_DATE ?=
DECISION_CREATE_RAW_TIMESTAMP ?=
DECISION_CREATE_MODE ?= sync
DECISION_CREATE_CONCURRENCY_LEVELS ?= 10,13,15,17,18
DECISION_CREATE_TENANT_ID ?= e83b4edf-570d-46af-9ff5-c189729a0897
DECISION_CREATE_SCENARIO_ID ?= 03b820dc-0457-4639-8a65-1b278141c56b
DECISION_CREATE_CALLBACK_URL ?=
NEXT_PUBLIC_SERVICE_BASE_URL ?= http://54.246.247.31
DECISION_ENGINE_FORWARDED_PORT ?= 8082
DURATION ?=
HOURS ?=
DAYS ?=
WEEKS ?=
BASE_URL ?= http://ec2-54-246-247-31.eu-west-1.compute.amazonaws.com
DATA_MODEL_URL ?=
INGESTION_URL ?=
DECISION_ENGINE_URL ?=
DECISION_CREATE_URL ?= $(NEXT_PUBLIC_SERVICE_BASE_URL):$(DECISION_ENGINE_FORWARDED_PORT)
TENANT_ID ?=
SCENARIO_ID ?=
TENANT_NAME ?= EC2 Production Replay Smoke Test
PUBLICATION_TIMEOUT ?= 900
SERVICE_AUTH_TOKEN ?=
TARGET_DB ?= fraud
BACKUP_DIR ?=
REUSE_DUMPS ?= true
DROP_LEGACY_DBS ?= true
ALLOW_EXISTING_TARGET ?= 0

production-replay:
	FRAUD_DATA_ROOT="$(DATA_ROOT)" \
	FRAUD_DATA_SEED_ROOT="$(SEED_DATA_ROOT)" \
	PRODUCTION_REPLAY_TRANSACTIONS="$(TRANSACTIONS)" \
	PRODUCTION_REPLAY_MULTIPLIER="$(MULTIPLIER)" \
	PRODUCTION_REPLAY_MAX_IN_FLIGHT="$(MAX_IN_FLIGHT)" \
	PRODUCTION_REPLAY_CHECKPOINT_EVERY="$(CHECKPOINT_EVERY)" \
	PRODUCTION_REPLAY_SEED_BATCH_SIZE="$(SEED_BATCH_SIZE)" \
	PRODUCTION_REPLAY_SEED_MAX_IN_FLIGHT="$(SEED_MAX_IN_FLIGHT)" \
	PRODUCTION_REPLAY_SEED_PROGRESS_EVERY="$(SEED_PROGRESS_EVERY)" \
	PRODUCTION_REPLAY_SEED_REQUEST_TIMEOUT="$(SEED_REQUEST_TIMEOUT)" \
	PRODUCTION_REPLAY_REUSE_EXISTING_SETUP="$(REUSE_EXISTING_SETUP)" \
	PRODUCTION_REPLAY_DECISION_MODE="$(DECISION_MODE)" \
	PRODUCTION_REPLAY_ASYNC_WAIT_TIMEOUT_MS="$(ASYNC_WAIT_TIMEOUT_MS)" \
	PRODUCTION_REPLAY_ASYNC_CALLBACK_URL="$(ASYNC_CALLBACK_URL)" \
	PRODUCTION_REPLAY_ASYNC_CALLBACK_PORT="$(ASYNC_CALLBACK_PORT)" \
	PRODUCTION_REPLAY_ASYNC_CALLBACK_WAIT_TIMEOUT="$(ASYNC_CALLBACK_WAIT_TIMEOUT)" \
	PRODUCTION_REPLAY_LIVE_DECISION_MODE="$(LIVE_DECISION_MODE)" \
	PRODUCTION_REPLAY_LIVE_ASYNC_FALLBACK_ENABLED="$(LIVE_ASYNC_FALLBACK_ENABLED)" \
	PRODUCTION_REPLAY_LIVE_ASYNC_OBJECT_TYPES="$(LIVE_ASYNC_OBJECT_TYPES)" \
	PRODUCTION_REPLAY_TENANT_DATA_READ_MODE="$(TENANT_DATA_READ_MODE)" \
	PRODUCTION_REPLAY_ENABLE_SEPARATE_READ_POOL="$(ENABLE_SEPARATE_READ_POOL)" \
	PRODUCTION_REPLAY_READ_DATABASE_URL="$(READ_DATABASE_URL)" \
	PRODUCTION_REPLAY_READ_DATABASE_MAX_CONNS="$(READ_DATABASE_MAX_CONNS)" \
	PRODUCTION_REPLAY_READ_DATABASE_MIN_CONNS="$(READ_DATABASE_MIN_CONNS)" \
	PRODUCTION_REPLAY_WORKER_DATABASE_URL="$(WORKER_DATABASE_URL)" \
	PRODUCTION_REPLAY_WORKER_DATABASE_MAX_CONNS="$(WORKER_DATABASE_MAX_CONNS)" \
	PRODUCTION_REPLAY_WORKER_DATABASE_MIN_CONNS="$(WORKER_DATABASE_MIN_CONNS)" \
	PRODUCTION_REPLAY_EXPERIMENT_LABEL="$(EXPERIMENT_LABEL)" \
	PRODUCTION_REPLAY_DURATION="$(DURATION)" \
	PRODUCTION_REPLAY_HOURS="$(HOURS)" \
	PRODUCTION_REPLAY_DAYS="$(DAYS)" \
	PRODUCTION_REPLAY_WEEKS="$(WEEKS)" \
	PRODUCTION_REPLAY_TENANT_ID="$(TENANT_ID)" \
	./backend/stress-tests/production_replay/run_local_replay.sh

replay-production: production-replay

production-replay-async: DECISION_MODE=async
production-replay-async: production-replay

production-replay-ec2:
	FRAUD_DATA_ROOT="$(DATA_ROOT)" \
	FRAUD_DATA_SEED_ROOT="$(SEED_DATA_ROOT)" \
	PRODUCTION_REPLAY_TRANSACTIONS="$(TRANSACTIONS)" \
	PRODUCTION_REPLAY_MULTIPLIER="$(MULTIPLIER)" \
	PRODUCTION_REPLAY_MAX_IN_FLIGHT="$(MAX_IN_FLIGHT)" \
	PRODUCTION_REPLAY_CHECKPOINT_EVERY="$(CHECKPOINT_EVERY)" \
	PRODUCTION_REPLAY_SEED_BATCH_SIZE="$(SEED_BATCH_SIZE)" \
	PRODUCTION_REPLAY_SEED_MAX_IN_FLIGHT="$(SEED_MAX_IN_FLIGHT)" \
	PRODUCTION_REPLAY_SEED_PROGRESS_EVERY="$(SEED_PROGRESS_EVERY)" \
	PRODUCTION_REPLAY_SEED_REQUEST_TIMEOUT="$(SEED_REQUEST_TIMEOUT)" \
	PRODUCTION_REPLAY_REUSE_EXISTING_SETUP="$(REUSE_EXISTING_SETUP)" \
	PRODUCTION_REPLAY_DECISION_MODE="$(DECISION_MODE)" \
	PRODUCTION_REPLAY_ASYNC_WAIT_TIMEOUT_MS="$(ASYNC_WAIT_TIMEOUT_MS)" \
	PRODUCTION_REPLAY_ASYNC_CALLBACK_URL="$(ASYNC_CALLBACK_URL)" \
	PRODUCTION_REPLAY_LIVE_DECISION_MODE="$(LIVE_DECISION_MODE)" \
	PRODUCTION_REPLAY_LIVE_ASYNC_FALLBACK_ENABLED="$(LIVE_ASYNC_FALLBACK_ENABLED)" \
	PRODUCTION_REPLAY_TENANT_DATA_READ_MODE="$(TENANT_DATA_READ_MODE)" \
	PRODUCTION_REPLAY_ENABLE_SEPARATE_READ_POOL="$(ENABLE_SEPARATE_READ_POOL)" \
	PRODUCTION_REPLAY_READ_DATABASE_MAX_CONNS="$(READ_DATABASE_MAX_CONNS)" \
	PRODUCTION_REPLAY_READ_DATABASE_MIN_CONNS="$(READ_DATABASE_MIN_CONNS)" \
	PRODUCTION_REPLAY_EXPERIMENT_LABEL="$(EXPERIMENT_LABEL)" \
	PRODUCTION_REPLAY_DURATION="$(DURATION)" \
	PRODUCTION_REPLAY_HOURS="$(HOURS)" \
	PRODUCTION_REPLAY_DAYS="$(DAYS)" \
	PRODUCTION_REPLAY_WEEKS="$(WEEKS)" \
	PRODUCTION_REPLAY_BASE_URL="$(BASE_URL)" \
	PRODUCTION_REPLAY_DATA_MODEL_URL="$(DATA_MODEL_URL)" \
	PRODUCTION_REPLAY_INGESTION_URL="$(INGESTION_URL)" \
	PRODUCTION_REPLAY_DECISION_ENGINE_URL="$(DECISION_ENGINE_URL)" \
	PRODUCTION_REPLAY_TENANT_ID="$(TENANT_ID)" \
	PRODUCTION_REPLAY_TENANT_NAME="$(TENANT_NAME)" \
	PRODUCTION_REPLAY_PUBLICATION_TIMEOUT="$(PUBLICATION_TIMEOUT)" \
	SERVICE_AUTH_TOKEN="$(SERVICE_AUTH_TOKEN)" \
	./backend/stress-tests/production_replay/run_remote_replay.sh

replay-production-ec2: production-replay-ec2

production-replay-ec2-async: DECISION_MODE=async
production-replay-ec2-async: production-replay-ec2

production-replay-matrix:
	$(if $(filter true,$(CAPTURE_METRICS)),CAPTURE_METRICS_FLAG=--capture-metrics, CAPTURE_METRICS_FLAG=) ; \
	cd backend && python3 stress-tests/production_replay_matrix.py \
		--target local \
		$(if $(filter true,$(EXECUTE)),--execute,) \
		$${CAPTURE_METRICS_FLAG} \
		--transactions "$(TRANSACTIONS)" \
		--multiplier "$(MULTIPLIER)" \
		--max-in-flight "$(MAX_IN_FLIGHT)" \
		--checkpoint-every "$(CHECKPOINT_EVERY)" \
		--tenant-id "$(TENANT_ID)"

callback-server:
	@mkdir -p "$$(dirname "$(CALLBACK_OUTPUT)")" "$$(dirname "$(CALLBACK_LOG)")"
	@echo "callback server: http://$(CALLBACK_HOST):$(CALLBACK_PORT)"
	@echo "callback output: $(CALLBACK_OUTPUT)"
	@echo "callback log: $(CALLBACK_LOG)"
	PYTHONPATH=backend/stress-tests python3 -m production_replay.callback_server \
		--host "$(CALLBACK_HOST)" \
		--port "$(CALLBACK_PORT)" \
		--output "$(CALLBACK_OUTPUT)" \
		2>&1 | tee -a "$(CALLBACK_LOG)"

create-decisions:
	DECISION_CREATE_EVENT_DATE="$(DECISION_CREATE_EVENT_DATE)" \
	DECISION_CREATE_RAW_TIMESTAMP="$(DECISION_CREATE_RAW_TIMESTAMP)" \
	PYTHONPATH=backend/stress-tests python3 -m production_replay.create_decisions \
		--decision-engine-url "$(if $(DECISION_ENGINE_URL),$(DECISION_ENGINE_URL),$(DECISION_CREATE_URL))" \
		--tenant-id "$(if $(TENANT_ID),$(TENANT_ID),$(DECISION_CREATE_TENANT_ID))" \
		--scenario-id "$(if $(SCENARIO_ID),$(SCENARIO_ID),$(DECISION_CREATE_SCENARIO_ID))" \
		--endpoint-mode "$(DECISION_CREATE_MODE)" \
		--count "$(COUNT)" \
		--concurrency-levels "$(DECISION_CREATE_CONCURRENCY_LEVELS)" \
		--wait-timeout-ms "$(ASYNC_WAIT_TIMEOUT_MS)" \
		--callback-url "$(DECISION_CREATE_CALLBACK_URL)" \
		--progress-every "$(PROGRESS_EVERY)" \
		--output "$(DECISION_CREATE_OUTPUT)"

create-async-decisions: DECISION_CREATE_MODE=async
create-async-decisions: DECISION_CREATE_CALLBACK_URL=$(ASYNC_CALLBACK_URL)
create-async-decisions: create-decisions

consolidate-postgres-db:
	TARGET_DB="$(TARGET_DB)" \
	BACKUP_DIR="$(BACKUP_DIR)" \
	REUSE_DUMPS="$(REUSE_DUMPS)" \
	DROP_LEGACY_DBS="$(DROP_LEGACY_DBS)" \
	ALLOW_EXISTING_TARGET="$(ALLOW_EXISTING_TARGET)" \
	bash ./backend/tools/db_consolidation/consolidate_to_fraud_db.sh
