ALTER TABLE core.async_decision_executions
  ADD COLUMN IF NOT EXISTS result_body JSONB NULL,
  ADD COLUMN IF NOT EXISTS callback_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS callback_status TEXT NULL,
  ADD COLUMN IF NOT EXISTS callback_attempt_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS callback_last_error TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS callback_sent_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ NULL;
