run:
	go run ./cmd/server

run-worker:
	go run ./cmd/worker

migrate-up:
	go run ./cmd/migrate up

migrate-down:
	go run ./cmd/migrate down

test:
	go test ./...

build:
	go build ./...

docker-up:
	docker compose up --build

docker-down:
	docker compose down
