import type { PortableDataModelDocument } from "@/lib/data-model-api";

export type DataModelTemplate = {
  id: string;
  name: string;
  sector: string;
  description: string;
  highlights: string[];
  document: PortableDataModelDocument;
};

export const dataModelTemplates: DataModelTemplate[] = [
  {
    id: "fintech-payments",
    name: "Fintech Payments",
    sector: "Fintech",
    description: "Accounts, merchants, processors, transactions, and payment flows.",
    highlights: [],
    document: {
      version: "v1",
      tables: [
        {
          name: "customers",
          description: "End customers using the payment platform",
          alias: "Customers",
          semantic_type: "customer",
          caption_field: "full_name",
          fields: [
            { name: "full_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "customer_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "individual", label: "Individual", sort_order: 10 },
              { value: "business", label: "Business", sort_order: 20 },
            ] },
            { name: "kyc_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "pending", label: "Pending", sort_order: 10 },
              { value: "approved", label: "Approved", sort_order: 20 },
              { value: "restricted", label: "Restricted", sort_order: 30 },
            ] },
            { name: "country_code", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
          ],
          options: { displayed_fields: ["full_name", "customer_type", "kyc_status"], field_order: ["full_name", "customer_type", "kyc_status", "country_code"] },
          navigation_options: [],
        },
        {
          name: "accounts",
          description: "Wallet, balance, or ledger accounts",
          alias: "Accounts",
          semantic_type: "finance",
          caption_field: "account_reference",
          fields: [
            { name: "customer_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "account_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "account_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "wallet", label: "Wallet", sort_order: 10 },
              { value: "settlement", label: "Settlement", sort_order: 20 },
              { value: "safeguarding", label: "Safeguarding", sort_order: 30 },
            ] },
            { name: "currency", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "usd", label: "USD", sort_order: 10 },
              { value: "gbp", label: "GBP", sort_order: 20 },
              { value: "eur", label: "EUR", sort_order: 30 },
            ] },
            { name: "account_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "restricted", label: "Restricted", sort_order: 20 },
              { value: "closed", label: "Closed", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["account_reference", "account_type", "currency", "account_status"], field_order: ["account_reference", "account_type", "currency", "account_status"] },
          navigation_options: [
            { source_field: "object_id", target_table: "transactions", filter_field: "account_id", ordering_field: "updated_at" },
          ],
        },
        {
          name: "merchants",
          description: "Billers, marketplaces, and merchant counterparties",
          alias: "Merchants",
          semantic_type: "merchant",
          caption_field: "merchant_name",
          fields: [
            { name: "merchant_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_category", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "retail", label: "Retail", sort_order: 10 },
              { value: "marketplace", label: "Marketplace", sort_order: 20 },
              { value: "utility", label: "Utility", sort_order: 30 },
              { value: "digital_goods", label: "Digital goods", sort_order: 40 },
            ] },
            { name: "settlement_currency", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "under_review", label: "Under review", sort_order: 20 },
              { value: "disabled", label: "Disabled", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["merchant_name", "merchant_category", "merchant_status"], field_order: ["merchant_name", "merchant_category", "settlement_currency", "merchant_status"] },
          navigation_options: [],
        },
        {
          name: "processors",
          description: "Acquirer, gateway, or switch partners",
          alias: "Processors",
          semantic_type: "reference",
          caption_field: "processor_name",
          fields: [
            { name: "processor_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "processor_role", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "gateway", label: "Gateway", sort_order: 10 },
              { value: "acquirer", label: "Acquirer", sort_order: 20 },
              { value: "switch", label: "Switch", sort_order: 30 },
            ] },
            { name: "region", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "degraded", label: "Degraded", sort_order: 20 },
              { value: "offline", label: "Offline", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["processor_name", "processor_role", "region", "processor_status"], field_order: ["processor_name", "processor_role", "region", "processor_status"] },
          navigation_options: [],
        },
        {
          name: "payment_intents",
          description: "Top-level payment requests before ledger posting",
          alias: "Payment Intents",
          semantic_type: "event",
          caption_field: "payment_reference",
          fields: [
            { name: "account_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "payment_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "channel", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "card", label: "Card", sort_order: 10 },
              { value: "bank_transfer", label: "Bank transfer", sort_order: 20 },
              { value: "wallet", label: "Wallet", sort_order: 30 },
            ] },
            { name: "intent_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "created", label: "Created", sort_order: 10 },
              { value: "authorized", label: "Authorized", sort_order: 20 },
              { value: "captured", label: "Captured", sort_order: 30 },
              { value: "cancelled", label: "Cancelled", sort_order: 40 },
            ] },
          ],
          options: { displayed_fields: ["payment_reference", "channel", "intent_status"], field_order: ["payment_reference", "account_id", "merchant_id", "channel", "intent_status"] },
          navigation_options: [
            { source_field: "object_id", target_table: "transactions", filter_field: "payment_intent_id", ordering_field: "updated_at" },
          ],
        },
        {
          name: "transactions",
          description: "Ledger-impacting payment events",
          alias: "Transactions",
          semantic_type: "transaction",
          caption_field: "transaction_reference",
          fields: [
            { name: "payment_intent_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "account_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "transaction_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "amount", description: "", data_type: "float", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "direction", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "debit", label: "Debit", sort_order: 10 },
              { value: "credit", label: "Credit", sort_order: 20 },
            ] },
            { name: "transaction_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "pending", label: "Pending", sort_order: 10 },
              { value: "posted", label: "Posted", sort_order: 20 },
              { value: "failed", label: "Failed", sort_order: 30 },
              { value: "reversed", label: "Reversed", sort_order: 40 },
            ] },
          ],
          options: { displayed_fields: ["transaction_reference", "amount", "direction", "transaction_status"], field_order: ["transaction_reference", "account_id", "merchant_id", "processor_id", "amount", "direction", "transaction_status"] },
          navigation_options: [],
        },
      ],
      links: [
        { name: "customer_account", parent_table: "customers", parent_field: "object_id", child_table: "accounts", child_field: "customer_id" },
        { name: "account_payment_intent", parent_table: "accounts", parent_field: "object_id", child_table: "payment_intents", child_field: "account_id" },
        { name: "merchant_payment_intent", parent_table: "merchants", parent_field: "object_id", child_table: "payment_intents", child_field: "merchant_id" },
        { name: "payment_intent_transaction", parent_table: "payment_intents", parent_field: "object_id", child_table: "transactions", child_field: "payment_intent_id" },
        { name: "account_transaction", parent_table: "accounts", parent_field: "object_id", child_table: "transactions", child_field: "account_id" },
        { name: "merchant_transaction", parent_table: "merchants", parent_field: "object_id", child_table: "transactions", child_field: "merchant_id" },
        { name: "processor_transaction", parent_table: "processors", parent_field: "object_id", child_table: "transactions", child_field: "processor_id" },
      ],
      pivots: [{ base_table: "transactions", path_links: ["account_transaction"] }],
    },
  },
  {
    id: "core-banking-deposits",
    name: "Core Banking Deposits",
    sector: "Banking",
    description: "Customers, deposit accounts, counterparties, and posted transactions.",
    highlights: [],
    document: {
      version: "v1",
      tables: [
        {
          name: "customers",
          description: "Retail and business banking customers",
          alias: "Customers",
          semantic_type: "customer",
          caption_field: "customer_name",
          fields: [
            { name: "customer_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "customer_segment", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "retail", label: "Retail", sort_order: 10 },
              { value: "sme", label: "SME", sort_order: 20 },
              { value: "corporate", label: "Corporate", sort_order: 30 },
            ] },
            { name: "residency_country", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "risk_rating", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "low", label: "Low", sort_order: 10 },
              { value: "medium", label: "Medium", sort_order: 20 },
              { value: "high", label: "High", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["customer_name", "customer_segment", "risk_rating"], field_order: ["customer_name", "customer_segment", "residency_country", "risk_rating"] },
          navigation_options: [],
        },
        {
          name: "accounts",
          description: "Current, savings, and term deposit accounts",
          alias: "Accounts",
          semantic_type: "finance",
          caption_field: "account_number",
          fields: [
            { name: "customer_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "account_number", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "account_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "current", label: "Current", sort_order: 10 },
              { value: "savings", label: "Savings", sort_order: 20 },
              { value: "term_deposit", label: "Term deposit", sort_order: 30 },
            ] },
            { name: "currency", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "usd", label: "USD", sort_order: 10 },
              { value: "gbp", label: "GBP", sort_order: 20 },
              { value: "eur", label: "EUR", sort_order: 30 },
            ] },
            { name: "account_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "open", label: "Open", sort_order: 10 },
              { value: "dormant", label: "Dormant", sort_order: 20 },
              { value: "blocked", label: "Blocked", sort_order: 30 },
              { value: "closed", label: "Closed", sort_order: 40 },
            ] },
          ],
          options: { displayed_fields: ["account_number", "account_type", "currency", "account_status"], field_order: ["account_number", "account_type", "currency", "account_status"] },
          navigation_options: [
            { source_field: "object_id", target_table: "transactions", filter_field: "account_id", ordering_field: "updated_at" },
          ],
        },
        {
          name: "counterparties",
          description: "External parties linked to transfers and payments",
          alias: "Counterparties",
          semantic_type: "reference",
          caption_field: "counterparty_name",
          fields: [
            { name: "counterparty_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "counterparty_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "individual", label: "Individual", sort_order: 10 },
              { value: "business", label: "Business", sort_order: 20 },
              { value: "bank", label: "Bank", sort_order: 30 },
            ] },
            { name: "bank_country", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "screening_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "clear", label: "Clear", sort_order: 10 },
              { value: "review", label: "Review", sort_order: 20 },
              { value: "blocked", label: "Blocked", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["counterparty_name", "counterparty_type", "screening_status"], field_order: ["counterparty_name", "counterparty_type", "bank_country", "screening_status"] },
          navigation_options: [],
        },
        {
          name: "transactions",
          description: "Posted debit and credit ledger entries",
          alias: "Transactions",
          semantic_type: "transaction",
          caption_field: "transaction_reference",
          fields: [
            { name: "account_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "counterparty_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "transaction_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "amount", description: "", data_type: "float", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "entry_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "debit", label: "Debit", sort_order: 10 },
              { value: "credit", label: "Credit", sort_order: 20 },
            ] },
            { name: "payment_rail", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "internal", label: "Internal", sort_order: 10 },
              { value: "ach", label: "ACH", sort_order: 20 },
              { value: "wire", label: "Wire", sort_order: 30 },
              { value: "rtgs", label: "RTGS", sort_order: 40 },
            ] },
            { name: "booking_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "pending", label: "Pending", sort_order: 10 },
              { value: "posted", label: "Posted", sort_order: 20 },
              { value: "returned", label: "Returned", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["transaction_reference", "amount", "entry_type", "booking_status"], field_order: ["transaction_reference", "account_id", "counterparty_id", "amount", "entry_type", "payment_rail", "booking_status"] },
          navigation_options: [],
        },
      ],
      links: [
        { name: "customer_account", parent_table: "customers", parent_field: "object_id", child_table: "accounts", child_field: "customer_id" },
        { name: "account_transaction", parent_table: "accounts", parent_field: "object_id", child_table: "transactions", child_field: "account_id" },
        { name: "counterparty_transaction", parent_table: "counterparties", parent_field: "object_id", child_table: "transactions", child_field: "counterparty_id" },
      ],
      pivots: [{ base_table: "transactions", path_links: ["account_transaction"] }],
    },
  },
  {
    id: "card-issuing",
    name: "Card Issuing",
    sector: "Banking",
    description: "Cardholders, cards, merchants, processors, authorizations, and clears.",
    highlights: [],
    document: {
      version: "v1",
      tables: [
        {
          name: "cardholders",
          description: "Individuals or businesses holding issued cards",
          alias: "Cardholders",
          semantic_type: "customer",
          caption_field: "cardholder_name",
          fields: [
            { name: "cardholder_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "customer_segment", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "consumer", label: "Consumer", sort_order: 10 },
              { value: "business", label: "Business", sort_order: 20 },
            ] },
            { name: "risk_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "standard", label: "Standard", sort_order: 10 },
              { value: "watchlist", label: "Watchlist", sort_order: 20 },
              { value: "restricted", label: "Restricted", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["cardholder_name", "customer_segment", "risk_status"], field_order: ["cardholder_name", "customer_segment", "risk_status"] },
          navigation_options: [],
        },
        {
          name: "accounts",
          description: "Funding or credit accounts behind cards",
          alias: "Accounts",
          semantic_type: "finance",
          caption_field: "account_reference",
          fields: [
            { name: "cardholder_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "account_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "account_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "prepaid", label: "Prepaid", sort_order: 10 },
              { value: "debit", label: "Debit", sort_order: 20 },
              { value: "credit", label: "Credit", sort_order: 30 },
            ] },
            { name: "account_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "open", label: "Open", sort_order: 10 },
              { value: "restricted", label: "Restricted", sort_order: 20 },
              { value: "closed", label: "Closed", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["account_reference", "account_type", "account_status"], field_order: ["account_reference", "account_type", "account_status"] },
          navigation_options: [],
        },
        {
          name: "cards",
          description: "Issued physical and virtual cards",
          alias: "Cards",
          semantic_type: "reference",
          caption_field: "masked_pan",
          fields: [
            { name: "account_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "masked_pan", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "card_product", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "consumer_debit", label: "Consumer debit", sort_order: 10 },
              { value: "consumer_credit", label: "Consumer credit", sort_order: 20 },
              { value: "business_prepaid", label: "Business prepaid", sort_order: 30 },
            ] },
            { name: "card_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "frozen", label: "Frozen", sort_order: 20 },
              { value: "cancelled", label: "Cancelled", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["masked_pan", "card_product", "card_status"], field_order: ["masked_pan", "card_product", "card_status"] },
          navigation_options: [
            { source_field: "object_id", target_table: "authorizations", filter_field: "card_id", ordering_field: "updated_at" },
            { source_field: "object_id", target_table: "transactions", filter_field: "card_id", ordering_field: "updated_at" },
          ],
        },
        {
          name: "merchants",
          description: "Acquiring merchants for card acceptance",
          alias: "Merchants",
          semantic_type: "merchant",
          caption_field: "merchant_name",
          fields: [
            { name: "merchant_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_country", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_category_code", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
          ],
          options: { displayed_fields: ["merchant_name", "merchant_country", "merchant_category_code"], field_order: ["merchant_name", "merchant_country", "merchant_category_code"] },
          navigation_options: [],
        },
        {
          name: "processors",
          description: "Scheme processor or issuer processing partner",
          alias: "Processors",
          semantic_type: "reference",
          caption_field: "processor_name",
          fields: [
            { name: "processor_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "scheme", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "visa", label: "Visa", sort_order: 10 },
              { value: "mastercard", label: "Mastercard", sort_order: 20 },
              { value: "domestic", label: "Domestic", sort_order: 30 },
            ] },
            { name: "processor_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "maintenance", label: "Maintenance", sort_order: 20 },
              { value: "offline", label: "Offline", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["processor_name", "scheme", "processor_status"], field_order: ["processor_name", "scheme", "processor_status"] },
          navigation_options: [],
        },
        {
          name: "authorizations",
          description: "Pre-clearing card authorization decisions",
          alias: "Authorizations",
          semantic_type: "event",
          caption_field: "authorization_code",
          fields: [
            { name: "card_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "authorization_code", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "amount", description: "", data_type: "float", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "authorization_result", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "approved", label: "Approved", sort_order: 10 },
              { value: "declined", label: "Declined", sort_order: 20 },
              { value: "reversed", label: "Reversed", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["authorization_code", "amount", "authorization_result"], field_order: ["authorization_code", "card_id", "merchant_id", "processor_id", "amount", "authorization_result"] },
          navigation_options: [
            { source_field: "object_id", target_table: "transactions", filter_field: "authorization_id", ordering_field: "updated_at" },
          ],
        },
        {
          name: "transactions",
          description: "Clearing and settlement card transactions",
          alias: "Transactions",
          semantic_type: "transaction",
          caption_field: "transaction_reference",
          fields: [
            { name: "authorization_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "card_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "transaction_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "amount", description: "", data_type: "float", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "clearing_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "cleared", label: "Cleared", sort_order: 10 },
              { value: "settled", label: "Settled", sort_order: 20 },
              { value: "chargeback", label: "Chargeback", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["transaction_reference", "amount", "clearing_status"], field_order: ["transaction_reference", "authorization_id", "card_id", "merchant_id", "processor_id", "amount", "clearing_status"] },
          navigation_options: [],
        },
      ],
      links: [
        { name: "cardholder_account", parent_table: "cardholders", parent_field: "object_id", child_table: "accounts", child_field: "cardholder_id" },
        { name: "account_card", parent_table: "accounts", parent_field: "object_id", child_table: "cards", child_field: "account_id" },
        { name: "card_authorization", parent_table: "cards", parent_field: "object_id", child_table: "authorizations", child_field: "card_id" },
        { name: "merchant_authorization", parent_table: "merchants", parent_field: "object_id", child_table: "authorizations", child_field: "merchant_id" },
        { name: "processor_authorization", parent_table: "processors", parent_field: "object_id", child_table: "authorizations", child_field: "processor_id" },
        { name: "authorization_transaction", parent_table: "authorizations", parent_field: "object_id", child_table: "transactions", child_field: "authorization_id" },
        { name: "card_transaction", parent_table: "cards", parent_field: "object_id", child_table: "transactions", child_field: "card_id" },
      ],
      pivots: [{ base_table: "transactions", path_links: ["card_transaction"] }],
    },
  },
  {
    id: "merchant-acquiring",
    name: "Merchant Acquiring",
    sector: "Fintech",
    description: "Merchants, stores, terminals, processors, transactions, and settlements.",
    highlights: [],
    document: {
      version: "v1",
      tables: [
        {
          name: "merchants",
          description: "Acquired merchants using the platform",
          alias: "Merchants",
          semantic_type: "merchant",
          caption_field: "merchant_name",
          fields: [
            { name: "merchant_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_segment", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "smb", label: "SMB", sort_order: 10 },
              { value: "mid_market", label: "Mid-market", sort_order: 20 },
              { value: "enterprise", label: "Enterprise", sort_order: 30 },
            ] },
            { name: "settlement_currency", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "merchant_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "under_review", label: "Under review", sort_order: 20 },
              { value: "paused", label: "Paused", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["merchant_name", "merchant_segment", "merchant_status"], field_order: ["merchant_name", "merchant_segment", "settlement_currency", "merchant_status"] },
          navigation_options: [],
        },
        {
          name: "stores",
          description: "Merchant branches, websites, or storefronts",
          alias: "Stores",
          semantic_type: "reference",
          caption_field: "store_name",
          fields: [
            { name: "merchant_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "store_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "channel", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "pos", label: "POS", sort_order: 10 },
              { value: "ecommerce", label: "Ecommerce", sort_order: 20 },
              { value: "mobile", label: "Mobile", sort_order: 30 },
            ] },
            { name: "country_code", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
          ],
          options: { displayed_fields: ["store_name", "channel", "country_code"], field_order: ["store_name", "merchant_id", "channel", "country_code"] },
          navigation_options: [],
        },
        {
          name: "processors",
          description: "Processors or gateways routing merchant traffic",
          alias: "Processors",
          semantic_type: "reference",
          caption_field: "processor_name",
          fields: [
            { name: "processor_name", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "processor_role", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "gateway", label: "Gateway", sort_order: 10 },
              { value: "acquirer", label: "Acquirer", sort_order: 20 },
              { value: "orchestrator", label: "Orchestrator", sort_order: 30 },
            ] },
            { name: "processor_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "degraded", label: "Degraded", sort_order: 20 },
              { value: "offline", label: "Offline", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["processor_name", "processor_role", "processor_status"], field_order: ["processor_name", "processor_role", "processor_status"] },
          navigation_options: [],
        },
        {
          name: "terminals",
          description: "Physical terminals or ecommerce terminal profiles",
          alias: "Terminals",
          semantic_type: "reference",
          caption_field: "terminal_label",
          fields: [
            { name: "store_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "terminal_label", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "terminal_type", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "countertop", label: "Countertop", sort_order: 10 },
              { value: "softpos", label: "SoftPOS", sort_order: 20 },
              { value: "hosted_checkout", label: "Hosted checkout", sort_order: 30 },
            ] },
            { name: "terminal_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "active", label: "Active", sort_order: 10 },
              { value: "disabled", label: "Disabled", sort_order: 20 },
              { value: "testing", label: "Testing", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["terminal_label", "terminal_type", "terminal_status"], field_order: ["terminal_label", "store_id", "processor_id", "terminal_type", "terminal_status"] },
          navigation_options: [
            { source_field: "object_id", target_table: "transactions", filter_field: "terminal_id", ordering_field: "updated_at" },
          ],
        },
        {
          name: "transactions",
          description: "Authorized or captured merchant payment events",
          alias: "Transactions",
          semantic_type: "transaction",
          caption_field: "transaction_reference",
          fields: [
            { name: "terminal_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "transaction_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "amount", description: "", data_type: "float", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "currency", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "authorization_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "approved", label: "Approved", sort_order: 10 },
              { value: "declined", label: "Declined", sort_order: 20 },
              { value: "reversed", label: "Reversed", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["transaction_reference", "amount", "currency", "authorization_status"], field_order: ["transaction_reference", "terminal_id", "processor_id", "amount", "currency", "authorization_status"] },
          navigation_options: [],
        },
        {
          name: "settlements",
          description: "Merchant settlement and payout events",
          alias: "Settlements",
          semantic_type: "event",
          caption_field: "settlement_reference",
          fields: [
            { name: "merchant_id", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "processor_id", description: "", data_type: "string", nullable: true, is_enum: false, is_unique: false, enum_values: [] },
            { name: "settlement_reference", description: "", data_type: "string", nullable: false, is_enum: false, is_unique: true, enum_values: [] },
            { name: "settlement_amount", description: "", data_type: "float", nullable: false, is_enum: false, is_unique: false, enum_values: [] },
            { name: "settlement_status", description: "", data_type: "string", nullable: false, is_enum: true, is_unique: false, enum_values: [
              { value: "scheduled", label: "Scheduled", sort_order: 10 },
              { value: "sent", label: "Sent", sort_order: 20 },
              { value: "returned", label: "Returned", sort_order: 30 },
            ] },
          ],
          options: { displayed_fields: ["settlement_reference", "settlement_amount", "settlement_status"], field_order: ["settlement_reference", "merchant_id", "processor_id", "settlement_amount", "settlement_status"] },
          navigation_options: [],
        },
      ],
      links: [
        { name: "merchant_store", parent_table: "merchants", parent_field: "object_id", child_table: "stores", child_field: "merchant_id" },
        { name: "store_terminal", parent_table: "stores", parent_field: "object_id", child_table: "terminals", child_field: "store_id" },
        { name: "processor_terminal", parent_table: "processors", parent_field: "object_id", child_table: "terminals", child_field: "processor_id" },
        { name: "terminal_transaction", parent_table: "terminals", parent_field: "object_id", child_table: "transactions", child_field: "terminal_id" },
        { name: "processor_transaction", parent_table: "processors", parent_field: "object_id", child_table: "transactions", child_field: "processor_id" },
        { name: "merchant_settlement", parent_table: "merchants", parent_field: "object_id", child_table: "settlements", child_field: "merchant_id" },
        { name: "processor_settlement", parent_table: "processors", parent_field: "object_id", child_table: "settlements", child_field: "processor_id" },
      ],
      pivots: [{ base_table: "transactions", path_links: ["terminal_transaction"] }],
    },
  },
];
